-- +goose Up
-- The Day entity (PRD §9, §5.1), owned by the trip module. Each trip's days are
-- derived from its date range; exactly one Day row per calendar date in
-- [start_date, end_date] is generated by Epic M03.2 S2–S3. The table is created
-- here in S1; generation logic lives in application code.
--
-- trip_id references trip.trips with a cascading delete: when a trip is removed
-- all its days disappear atomically with no orphan cleanup needed at the
-- application layer.
--
-- date is a Postgres DATE (calendar day, no time zone). index gives a stable
-- within-trip ordinal (0-based) mirroring date order; it lets later milestones
-- address a day by position without recomputing from date arithmetic.
--
-- notes is a plain text field seeded empty; later milestones (journal, planning)
-- layer their own tables on top of the Day rather than overloading this column.
--
-- The UNIQUE constraint on (trip_id, date) is the idempotency key for generation:
-- S2–S3 can upsert or insert-ignore without producing duplicates even if called
-- more than once.
CREATE TABLE trip.days (
    id       uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
    trip_id  uuid    NOT NULL REFERENCES trip.trips (id) ON DELETE CASCADE,
    date     date    NOT NULL,
    index    integer NOT NULL,
    notes    text    NOT NULL DEFAULT '',
    CONSTRAINT days_trip_date_unique UNIQUE (trip_id, date)
);

-- Per-trip reads (listing all days for a trip) filter on trip_id.
CREATE INDEX days_trip_id_idx ON trip.days (trip_id);

-- +goose Down
DROP TABLE trip.days;
