package sharing

import (
	"context"
	"errors"
	"fmt"
	"net/mail"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// InvitationStatus is the lifecycle state of an invitation.
type InvitationStatus string

const (
	StatusSent     InvitationStatus = "sent"
	StatusAccepted InvitationStatus = "accepted"
	StatusRevoked  InvitationStatus = "revoked"
	// StatusDeclined is set when the recipient turns down an invitation. It is
	// terminal like StatusRevoked, so a declined invite can no longer be claimed
	// and drops out of both the recipient's inbox and the owner's pending list.
	StatusDeclined InvitationStatus = "declined"
)

// ErrInvitationNotFound is returned when no invitation matches the lookup.
var ErrInvitationNotFound = errors.New("sharing: invitation not found")

// ErrInvitationAlreadyClaimed is returned when attempting to accept an
// invitation that has already been accepted or revoked.
var ErrInvitationAlreadyClaimed = errors.New("sharing: invitation already accepted or revoked")

// ErrEmailMismatch is returned when the accepting user's email does not match
// the invitation email.
var ErrEmailMismatch = errors.New("sharing: invitation email does not match signed-in user")

// Invitation is a single row from sharing.invitations.
type Invitation struct {
	ID     string
	TripID string
	Email  string
	Role   Role
	Status InvitationStatus
	Token  string
}

// Invitations manages the invitation lifecycle in sharing.invitations.
type Invitations struct {
	pool *pgxpool.Pool
}

// NewInvitations constructs the invitation store.
func NewInvitations(pool *pgxpool.Pool) *Invitations { return &Invitations{pool: pool} }

// Create inserts a new invitation with status=sent. token must be an
// unguessable value generated by the caller (e.g. a random UUID).
func (inv *Invitations) Create(ctx context.Context, tripID, email, token string, role Role) (Invitation, error) {
	const query = `
		INSERT INTO sharing.invitations (trip_id, email, role, token)
		VALUES ($1::uuid, $2, $3, $4)
		RETURNING id::text, trip_id::text, email, role, status, token`
	var i Invitation
	var roleStr, statusStr string
	err := inv.pool.QueryRow(ctx, query, tripID, email, string(role), token).
		Scan(&i.ID, &i.TripID, &i.Email, &roleStr, &statusStr, &i.Token)
	if err != nil {
		return Invitation{}, fmt.Errorf("sharing: create invitation: %w", err)
	}
	i.Role = Role(roleStr)
	i.Status = InvitationStatus(statusStr)
	return i, nil
}

// ByToken looks up an invitation by its token. Returns ErrInvitationNotFound
// when no row matches.
func (inv *Invitations) ByToken(ctx context.Context, token string) (Invitation, error) {
	const query = `
		SELECT id::text, trip_id::text, email, role, status, token
		FROM sharing.invitations
		WHERE token = $1`
	var i Invitation
	var roleStr, statusStr string
	err := inv.pool.QueryRow(ctx, query, token).
		Scan(&i.ID, &i.TripID, &i.Email, &roleStr, &statusStr, &i.Token)
	if errors.Is(err, pgx.ErrNoRows) {
		return Invitation{}, ErrInvitationNotFound
	}
	if err != nil {
		return Invitation{}, fmt.Errorf("sharing: invitation by token: %w", err)
	}
	i.Role = Role(roleStr)
	i.Status = InvitationStatus(statusStr)
	return i, nil
}

// ForTrip returns all invitations for the given trip, ordered by creation time.
func (inv *Invitations) ForTrip(ctx context.Context, tripID string) ([]Invitation, error) {
	const query = `
		SELECT id::text, trip_id::text, email, role, status, token
		FROM sharing.invitations
		WHERE trip_id = $1::uuid
		ORDER BY created_at`
	rows, err := inv.pool.Query(ctx, query, tripID)
	if err != nil {
		return nil, fmt.Errorf("sharing: invitations for trip: %w", err)
	}
	defer rows.Close()
	var out []Invitation
	for rows.Next() {
		var i Invitation
		var roleStr, statusStr string
		if err := rows.Scan(&i.ID, &i.TripID, &i.Email, &roleStr, &statusStr, &i.Token); err != nil {
			return nil, fmt.Errorf("sharing: scan invitation: %w", err)
		}
		i.Role = Role(roleStr)
		i.Status = InvitationStatus(statusStr)
		out = append(out, i)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("sharing: invitations for trip rows: %w", err)
	}
	return out, nil
}

// AcceptInTx marks the invitation identified by token as accepted and creates a
// TripMembership within the caller-supplied transaction. This backs the
// email-link accept flow. See acceptLocked for the matching rules.
func (inv *Invitations) AcceptInTx(ctx context.Context, tx pgx.Tx, token, userID, userEmail string) (Invitation, error) {
	const lockQuery = `
		SELECT id::text, trip_id::text, email, role, status, token
		FROM sharing.invitations
		WHERE token = $1
		FOR UPDATE`
	i, err := scanLockedInvitation(tx.QueryRow(ctx, lockQuery, token))
	if err != nil {
		return Invitation{}, err
	}
	return inv.acceptLocked(ctx, tx, i, userID, userEmail)
}

// AcceptByIDInTx is AcceptInTx keyed on the invitation's id instead of its
// opaque token. It backs the in-app invitation inbox, where a recipient accepts
// an invitation surfaced by PendingForEmail and so never has the token (which
// only ever travels in the invite email). The email match in acceptLocked is
// still the real authorization: id alone does not grant access.
func (inv *Invitations) AcceptByIDInTx(ctx context.Context, tx pgx.Tx, invitationID, userID, userEmail string) (Invitation, error) {
	const lockQuery = `
		SELECT id::text, trip_id::text, email, role, status, token
		FROM sharing.invitations
		WHERE id = $1::uuid
		FOR UPDATE`
	i, err := scanLockedInvitation(tx.QueryRow(ctx, lockQuery, invitationID))
	if err != nil {
		return Invitation{}, err
	}
	return inv.acceptLocked(ctx, tx, i, userID, userEmail)
}

// scanLockedInvitation scans a FOR UPDATE lock row into an Invitation, mapping a
// missing row to ErrInvitationNotFound.
func scanLockedInvitation(row pgx.Row) (Invitation, error) {
	var i Invitation
	var roleStr, statusStr string
	err := row.Scan(&i.ID, &i.TripID, &i.Email, &roleStr, &statusStr, &i.Token)
	if errors.Is(err, pgx.ErrNoRows) {
		return Invitation{}, ErrInvitationNotFound
	}
	if err != nil {
		return Invitation{}, fmt.Errorf("sharing: lock invitation: %w", err)
	}
	i.Role = Role(roleStr)
	i.Status = InvitationStatus(statusStr)
	return i, nil
}

// acceptLocked applies the accept transition to an already-locked invitation
// row: the accepting user's email must match the invitation's (case-insensitive,
// whitespace-trimmed) and the invitation must still be in 'sent' state. It marks
// the invitation accepted and creates the membership in the same transaction.
// Returns ErrEmailMismatch on a mismatch and ErrInvitationAlreadyClaimed if the
// invitation is not 'sent'.
func (inv *Invitations) acceptLocked(ctx context.Context, tx pgx.Tx, i Invitation, userID, userEmail string) (Invitation, error) {
	if i.Status != StatusSent {
		return Invitation{}, ErrInvitationAlreadyClaimed
	}
	if !emailsEqual(i.Email, userEmail) {
		return Invitation{}, ErrEmailMismatch
	}

	const acceptQuery = `
		UPDATE sharing.invitations
		SET status = 'accepted', updated_at = now()
		WHERE id = $1::uuid`
	if _, err := tx.Exec(ctx, acceptQuery, i.ID); err != nil {
		return Invitation{}, fmt.Errorf("sharing: accept invitation update: %w", err)
	}

	const memberQuery = `
		INSERT INTO sharing.trip_memberships (trip_id, user_id, role)
		VALUES ($1::uuid, $2::uuid, $3)
		ON CONFLICT (trip_id, user_id) DO NOTHING`
	if _, err := tx.Exec(ctx, memberQuery, i.TripID, userID, string(i.Role)); err != nil {
		return Invitation{}, fmt.Errorf("sharing: accept invitation create membership: %w", err)
	}

	i.Status = StatusAccepted
	return i, nil
}

// PendingInvitation is a still-pending invitation joined with its trip's name,
// for the in-app inbox that lists invitations waiting for the signed-in user.
type PendingInvitation struct {
	ID       string
	TripID   string
	TripName string
	Role     Role
}

// PendingForEmail returns every still-pending (status='sent') invitation
// addressed to email, joined with the trip name for display, newest last. The
// match is case-insensitive (Google emails are), so it surfaces invites
// regardless of how the owner typed the address. This is the read side of the
// in-app invitation inbox: a recipient can join a shared trip by opening the app
// even when no invite email was ever delivered.
func (inv *Invitations) PendingForEmail(ctx context.Context, email string) ([]PendingInvitation, error) {
	const query = `
		SELECT i.id::text, i.trip_id::text, COALESCE(t.name, ''), i.role
		FROM sharing.invitations i
		JOIN trip.trips t ON t.id = i.trip_id
		WHERE i.status = 'sent' AND lower(i.email) = lower($1)
		ORDER BY i.created_at`
	rows, err := inv.pool.Query(ctx, query, email)
	if err != nil {
		return nil, fmt.Errorf("sharing: pending invitations for email: %w", err)
	}
	defer rows.Close()
	var out []PendingInvitation
	for rows.Next() {
		var p PendingInvitation
		var roleStr string
		if err := rows.Scan(&p.ID, &p.TripID, &p.TripName, &roleStr); err != nil {
			return nil, fmt.Errorf("sharing: scan pending invitation: %w", err)
		}
		p.Role = Role(roleStr)
		out = append(out, p)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("sharing: pending invitations rows: %w", err)
	}
	return out, nil
}

// RevokeInvitation sets a pending invitation's status to 'revoked'. Returns
// ErrInvitationNotFound when no row matches and ErrInvitationAlreadyClaimed
// when the invitation has already been accepted.
func (inv *Invitations) RevokeInvitation(ctx context.Context, invitationID string) error {
	const query = `
		UPDATE sharing.invitations
		SET status = 'revoked', updated_at = now()
		WHERE id = $1::uuid AND status = 'sent'`
	tag, err := inv.pool.Exec(ctx, query, invitationID)
	if err != nil {
		return fmt.Errorf("sharing: revoke invitation: %w", err)
	}
	if tag.RowsAffected() == 0 {
		// Either not found or already accepted/revoked — check which.
		var status string
		err2 := inv.pool.QueryRow(ctx,
			`SELECT status FROM sharing.invitations WHERE id = $1::uuid`, invitationID).
			Scan(&status)
		if errors.Is(err2, pgx.ErrNoRows) {
			return ErrInvitationNotFound
		}
		return ErrInvitationAlreadyClaimed
	}
	return nil
}

// DeclineByID marks the invitation identified by id as 'declined' on behalf of
// its recipient. userEmail must match the invitation's email (case-insensitive,
// whitespace-trimmed) — the id alone does not authorize the decline, so one user
// cannot decline another's invitation by guessing an id. Returns
// ErrInvitationNotFound when no row matches, ErrEmailMismatch when the invite
// was addressed to a different email, and ErrInvitationAlreadyClaimed when the
// invitation is no longer pending (already accepted, revoked, or declined).
func (inv *Invitations) DeclineByID(ctx context.Context, invitationID, userEmail string) error {
	const selectQuery = `
		SELECT email, status
		FROM sharing.invitations
		WHERE id = $1::uuid`
	var email, status string
	err := inv.pool.QueryRow(ctx, selectQuery, invitationID).Scan(&email, &status)
	if errors.Is(err, pgx.ErrNoRows) {
		return ErrInvitationNotFound
	}
	if err != nil {
		return fmt.Errorf("sharing: decline invitation lookup: %w", err)
	}
	if !emailsEqual(email, userEmail) {
		return ErrEmailMismatch
	}
	if InvitationStatus(status) != StatusSent {
		return ErrInvitationAlreadyClaimed
	}

	const declineQuery = `
		UPDATE sharing.invitations
		SET status = 'declined', updated_at = now()
		WHERE id = $1::uuid AND status = 'sent'`
	tag, err := inv.pool.Exec(ctx, declineQuery, invitationID)
	if err != nil {
		return fmt.Errorf("sharing: decline invitation: %w", err)
	}
	if tag.RowsAffected() == 0 {
		// Raced with another accept/revoke/decline between our read and write.
		return ErrInvitationAlreadyClaimed
	}
	return nil
}

// emailsEqual compares two email addresses case-insensitively, ignoring any
// surrounding whitespace. Google emails are case-insensitive by convention, and
// trimming guards against a stray space slipping into either side (a mismatch
// here silently locks the recipient out of the trip).
func emailsEqual(a, b string) bool {
	return strings.EqualFold(strings.TrimSpace(a), strings.TrimSpace(b))
}

// normalizeEmail trims surrounding whitespace and lowercases an email address so
// invitations are stored in the same shape a recipient's verified sign-in email
// compares against. It returns ok=false when raw is empty or not a syntactically
// valid address, so a typo can't create an invitation nobody can ever accept.
func normalizeEmail(raw string) (email string, ok bool) {
	addr, err := mail.ParseAddress(strings.TrimSpace(raw))
	if err != nil {
		return "", false
	}
	// Require a dotted domain (e.g. example.com): net/mail on its own accepts
	// dotless hosts like "user@localhost" that no real recipient would sign in
	// with, which is exactly the un-acceptable invite we're guarding against.
	at := strings.LastIndex(addr.Address, "@")
	if at < 0 || !strings.Contains(addr.Address[at+1:], ".") {
		return "", false
	}
	return strings.ToLower(addr.Address), true
}
