package auth

import "context"

// VerifiedIdentity holds the user attributes extracted from a verified Google
// ID token. Values here are trusted only after the token has passed signature,
// audience, issuer, expiry, and nonce validation (S3).
type VerifiedIdentity struct {
	GoogleSub string // "sub" claim — stable Google account identifier
	Email     string
	Name      string
	Avatar    string // picture URL
}

// IdentityProvider wraps the Google OAuth 2.0 / OIDC sign-in flow behind a
// seam so the underlying provider can be swapped without touching callers
// (PRD §7.0). The two operations map to the two legs of the authorization-code
// flow: building the consent redirect URL (with CSRF/replay protection) and
// exchanging the callback code for a verified identity.
type IdentityProvider interface {
	// AuthCodeURL returns the Google consent URL for a new sign-in attempt.
	// state and nonce are per-request random values generated by the caller
	// (S2); the provider embeds them in the URL so the callback can verify
	// them (S3).
	AuthCodeURL(state, nonce string) string

	// Exchange swaps the authorization code for tokens and validates the ID
	// token (signature, audience, issuer, expiry) before returning a trusted
	// VerifiedIdentity. expectedNonce is the nonce minted at /auth/login (read
	// back from the signed state cookie); the ID token's nonce claim must match
	// it, closing the replay window. State verification (CSRF) happens in the
	// callback handler before Exchange is called.
	Exchange(ctx context.Context, code, expectedNonce string) (VerifiedIdentity, error)
}
